language: objective-c
osx_image: xcode7
script:
- xcodebuild -project Examples/RDHCollectionViewGridLayoutDemo.xcodeproj -scheme RDHCollectionViewGridLayoutDemo -destination "platform=iOS Simulator,name=iPhone 6" clean build test