language: objective-c
osx_image: xcode7.2
script:
# Build framework
- xcodebuild -project Examples/RDHCollectionViewGridLayoutDemo.xcodeproj -scheme RDHCollectionViewGridLayout clean build CODE_SIGN_IDENTITY=
- xcodebuild -project Examples/RDHCollectionViewGridLayoutDemo.xcodeproj -scheme RDHCollectionViewGridLayoutDemo -destination "platform=iOS Simulator,name=iPhone 6" clean build test
#- xcodebuild -project Examples/RDHCollectionViewGridLayoutDemo.xcodeproj -scheme RDHCollectionViewGridLayoutDemo -destination "platform=tvOS Simulator,name=Apple TV 1080p" clean build test